# --
# Kernel/System/PostMaster/Filter/NewTicketOnlyFromKnowEmail.pm - sub part of PostMaster.pm
# --
# This software comes with ABSOLUTELY NO WARRANTY. For details, see
# the enclosed file COPYING for license information (AGPL). If you
# did not receive this file, see http://www.gnu.org/licenses/agpl.txt.
# --

package Kernel::System::PostMaster::Filter::NewTicketOnlyFromKnowEmail;

use strict;
use warnings;

our @ObjectDependencies = (
    'Kernel::Config',
    'Kernel::System::Email',
    'Kernel::System::EmailParser',
    'Kernel::System::Log',
    'Kernel::System::CustomerUser',
    'Kernel::System::Ticket',
    'Kernel::System::PostMaster::LoopProtection',
);

sub new {
    my ( $Type, %Param ) = @_;

    # allocate new hash for object
    my $Self = {};
    bless( $Self, $Type );
	
	# get parser object
    $Self->{ParserObject} = $Param{ParserObject} || die "Got no ParserObject!";

    $Self->{Debug} = $Param{Debug} || 0;

    return $Self;
}

sub Run {
    my ( $Self, %Param ) = @_;

    # check needed stuff
    for (qw(JobConfig GetParam)) {
        if ( !$Param{$_} ) {
             $Kernel::OM->Get('Kernel::System::Log')->Log(
                Priority => 'error',
                Message  => "Need $_!"
            );
            return;
        }
    }
	
    # get config options
    my %Config;
    my %Match;
    my %Set;
    if ( $Param{JobConfig} && ref $Param{JobConfig} eq 'HASH' ) {
        %Config = %{ $Param{JobConfig} };
        if ( $Config{Match} ) {
            %Match = %{ $Config{Match} };
        }
        if ( $Config{Set} ) {
            %Set = %{ $Config{Set} };			
        }
    }    
	
    # get sender email
    my @EmailAddresses = $Self->{ParserObject}->SplitAddressLine( Line => $Param{GetParam}->{From}, );
	
    for (@EmailAddresses) {
        $Param{GetParam}->{SenderEmailAddress} = $Self->{ParserObject}->GetEmailAddress( Email => $_, );
    }

    my %List = $Kernel::OM->Get('Kernel::System::CustomerUser')->CustomerSearch(
        PostMasterSearch => lc( $Param{GetParam}->{SenderEmailAddress} ),
    );
    my %CustomerData;
    for ( keys %List ) {
        %CustomerData = $Kernel::OM->Get('Kernel::System::CustomerUser')->CustomerUserDataGet(
            User => $_,
        );
    }

    # if there is no customer id found!
    if ( !$CustomerData{UserLogin} ) {
	# RETURN IF NO CUSTOMER ID
	$Kernel::OM->Get('Kernel::System::Log')->Log( Priority => 'info', Message => $Param{GetParam}->{SenderEmailAddress} . " not in database" );

		# get ticket object
        my $TicketObject = $Kernel::OM->Get('Kernel::System::Ticket');		
		
        # check if new ticket
        my $Tn = $TicketObject->GetTNByString( $Param{GetParam}->{Subject} );
		
        return 1 if $Tn && $TicketObject->TicketCheckNumber( Tn => $Tn );

        # set attributes if ticket is created
        for ( keys %Set ) {
            $Param{GetParam}->{$_} = $Set{$_};
            $Kernel::OM->Get('Kernel::System::Log')->Log(
                Priority => 'notice',
                Message =>
                    "Set param '$_' to '$Set{$_}' (Message-ID: $Param{GetParam}->{'Message-ID'}) ",
            );
        }
		
		 # get config object
        my $ConfigObject = $Kernel::OM->Get('Kernel::Config');

        # send bounce mail
        my $Subject = $ConfigObject->Get(
            'PostMaster::PreFilterModule::NewTicketOnlyFromKnowEmail::Subject'
        );
        my $Body = $ConfigObject->Get(
            'PostMaster::PreFilterModule::NewTicketOnlyFromKnowEmail::Body'
        );
        my $Sender = $ConfigObject->Get(
            'PostMaster::PreFilterModule::NewTicketOnlyFromKnowEmail::Sender'
        ) || '';

        # Don't reply to an email that already announces it doesn't want an auto-response
        # (mailing list traffic, a previous auto-response, or another system's bounce).
        # This mirrors the check Kernel::System::Ticket::Article::Backend::Email already
        # does for the built-in auto-responder, applied here because PreFilterModules run
        # before PostMaster.pm derives its own 'X-OTRS-Loop' flag from these same headers.
        my $IsAutoGenerated = $Param{GetParam}->{'Mailing-List'}
            || $Param{GetParam}->{'Precedence'}
            || $Param{GetParam}->{'X-Loop'}
            || $Param{GetParam}->{'X-No-Loop'}
            || $Param{GetParam}->{'X-OTRS-Loop'}
            || (
                $Param{GetParam}->{'Auto-Submitted'}
                && substr( $Param{GetParam}->{'Auto-Submitted'}, 0, 5 ) eq 'auto-'
            );

        if ($IsAutoGenerated) {
            $Kernel::OM->Get('Kernel::System::Log')->Log(
                Priority => 'notice',
                Message  =>
                    "Sent no reject mail to '$Param{GetParam}->{From}' because the sender "
                    . "doesn't want an auto-response (e. g. loop or precedence header)!",
            );
            return 1;
        }

        my $SenderAddress = $Param{GetParam}->{SenderEmailAddress};

        # Never reply to ourselves: this is the exact failure mode that caused the loop
        # incident of 2026-08 (an auto-response ends up addressed back to this same
        # mailbox, gets re-fetched, and triggers another auto-response, forever).
        if ( $SenderAddress && lc $SenderAddress eq lc $Sender ) {
            $Kernel::OM->Get('Kernel::System::Log')->Log(
                Priority => 'notice',
                Message  =>
                    "Sent no reject mail because sender '$SenderAddress' is our own "
                    . "notification address - would create a mail loop!",
            );
            return 1;
        }

        # Standard PostMaster rate limit per recipient (same mechanism the built-in
        # auto-responder uses), as defense in depth against any other loop shape.
        my $LoopProtectionObject = $Kernel::OM->Get('Kernel::System::PostMaster::LoopProtection');
        if ( $SenderAddress && !$LoopProtectionObject->Check( To => $SenderAddress ) ) {
            $Kernel::OM->Get('Kernel::System::Log')->Log(
                Priority => 'notice',
                Message  => "Sent no reject mail to '$SenderAddress' because of loop protection!",
            );
            return 1;
        }

        $Kernel::OM->Get('Kernel::System::Email')->Send(
            From       => $Sender,
            To         => $Param{GetParam}->{From},
            Subject    => $Subject,
            Body       => $Body,
            Charset    => 'utf-8',
            MimeType   => 'text/plain',
            Loop       => 1,
            Attachment => [
                {
                    Filename    => 'email.txt',
                    Content     => $Param{GetParam}->{Body},
                    ContentType => 'application/octet-stream',
                }
            ],
        );

        $LoopProtectionObject->SendEmail( To => $SenderAddress ) if $SenderAddress;

        $Kernel::OM->Get('Kernel::System::Log')->Log(
            Priority => 'notice',
            Message  => "Send reject mail to '$Param{GetParam}->{From}'!",
        );

    }
    return 1;
}

1;
