# --
# Copyright (C) 2001-2018 OTRS AG, http://otrs.com/
# --
# This software comes with ABSOLUTELY NO WARRANTY. For details, see
# the enclosed file COPYING for license information (AGPL). If you
# did not receive this file, see http://www.gnu.org/licenses/agpl.txt.
# --

package Kernel::GenericInterface::Operation::MiscLigero::QueueByGroupSearch;

use strict;
use warnings;

use Kernel::System::VariableCheck qw( :all );

use base qw(
    Kernel::GenericInterface::Operation::Common
);

our $ObjectManagerDisabled = 1;

=head1 NAME

Kernel::GenericInterface::Operation::MiscLigero::QueueByGroupSearch - Queue search by groups

=head1 PUBLIC INTERFACE

=over 4

=cut

=item new()

usually, you want to create an instance of this
by using Kernel::GenericInterface::Operation->new();

=cut

sub new {
    my ( $Type, %Param ) = @_;

    my $Self = {};
    bless( $Self, $Type );

    # check needed objects
    for my $Needed (qw(DebuggerObject WebserviceID)) {
        if ( !$Param{$Needed} ) {
            return {
                Success      => 0,
                ErrorMessage => "Got no $Needed!",
            };
        }

        $Self->{$Needed} = $Param{$Needed};
    }

    # get config for this screen
    #$Self->{Config} = $Kernel::OM->Get('Kernel::Config')->Get('GenericInterface::Operation::QueueByGroupSearch');

    return $Self;
}
=pod
@api {post} /generalcatalog/get List itens inside a class from GeneralCatalog.
@apiName Get
@apiGroup General Catalog
@apiVersion 1.0.0

@apiExample Example usage:
  {
    "SessionID": "560b2vVuwffhpoADg5RcpZiqJHcxpM4I",
    "GroupName": "ITSM::ConfigItem::Class"
  }

@apiParam (Request body) {String} [UserLogin] User login to create sesssion.
@apiParam (Request body) {String} [Password] Password to create session.
@apiParam (Request body) {String} SessionID session id generated by session create method.
@apiParam (Request body) {String} GroupName

@apiErrorExample {json} Error example:
  HTTP/1.1 200 Success
  {
    "Error": {
      "ErrorCode": "QueueByGroupSearch.AuthFail",
      "ErrorMessage": "QueueByGroupSearch: Authorization failing!"
    }
  }
@apiSuccessExample {json} Success example:
  HTTP/1.1 200 Success
  {
    "Items": [
      {
        "Key": "26",
        "Value": "Software"
      },
      {
        "Key": "135",
        "Value": "PortalService"
      },
      {
        "Key": "25",
        "Value": "Network"
      },
      {
        "Key": "22",
        "Value": "Computer"
      },
      {
        "Key": "23",
        "Value": "Hardware"
      },
      {
        "Key": "24",
        "Value": "Location"
      }
    ]
  }

@apiSuccess {Array} Items List of Items found.
=cut
sub Run {
    my ( $Self, %Param ) = @_;

    my ( $UserID, $UserType ) = $Self->Auth(
        %Param,
    );

    return $Self->ReturnError(
        ErrorCode    => 'QueueByGroupSearch.AuthFail',
        ErrorMessage => "QueueByGroupSearch: Authorization failing!",
    ) if !$UserID;

    return $Self->ReturnError(
        ErrorCode    => 'QueueByGroupSearch.ParamFail',
        ErrorMessage => "QueueByGroupSearch: Param GroupName is Required!",
    ) if !$Param{Data}->{GroupName};

    my $QueueObject = $Kernel::OM->Get('Kernel::System::Queue');

    my $GroupName =$Param{Data}->{GroupName};

    my $CacheKey;
    if ( $UserID ) {

        # get group list
        my %GroupList = $Kernel::OM->Get('Kernel::System::Group')->GroupList(
            Valid => 1,
        );

        return $Self->ReturnError(
            ErrorCode    => 'QueueByGroupSearch.SearchFail',
            ErrorMessage => "QueueByGroupSearch: Param GroupName not found!",
        ) if !%GroupList;

        my %Queues = $QueueObject->GetAllQueues();

        return $Self->ReturnError(
            ErrorCode    => 'QueueByGroupSearch.SearchFail',
            ErrorMessage => "QueueByGroupSearch: Queues not found!",
        ) if !%Queues;        

        my %GroupListReverse = reverse %GroupList; 

        my @values = ();

        if($GroupListReverse{$GroupName}){

            while (my ($key, $value) = each (%Queues)){
                my $GroupID = $QueueObject->GetQueueGroupID( QueueID => $key );
                push @values,{Key=>$key,Value=>$value} if ( $GroupID && $GroupID == $GroupListReverse{$GroupName} );
            }                       

            return {
                Success => 1,
                Data    => {
                    Queues => \@values
                },
            };
        }

        return {
            Success => 1,
            Data    => {},
        };        

    }

}

1;

=back

=head1 TERMS AND CONDITIONS

This software is part of the OTRS project (L<http://otrs.org/>).

This software comes with ABSOLUTELY NO WARRANTY. For details, see
the enclosed file COPYING for license information (AGPL). If you
did not receive this file, see L<http://www.gnu.org/licenses/agpl.txt>.

=cut