# --
# Copyright (C) 2001-2018 OTRS AG, http://otrs.com/
# --
# This software comes with ABSOLUTELY NO WARRANTY. For details, see
# the enclosed file COPYING for license information (AGPL). If you
# did not receive this file, see http://www.gnu.org/licenses/agpl.txt.
# --

package Kernel::GenericInterface::Operation::TicketLigero::ArticleAttachmentGet;

use strict;
use warnings;

use Kernel::System::VariableCheck qw( :all );

use base qw(
    Kernel::GenericInterface::Operation::Common
    Kernel::GenericInterface::Operation::Ticket::Common
);

our $ObjectManagerDisabled = 1;

=head1 NAME

Kernel::GenericInterface::Operation::TicketLigero::TypeSearch - GenericInterface Queues List

=head1 PUBLIC INTERFACE

=over 4

=cut

=item new()

usually, you want to create an instance of this
by using Kernel::GenericInterface::Operation->new();

=cut

sub new {
    my ( $Type, %Param ) = @_;

    my $Self = {};
    bless( $Self, $Type );

    # check needed objects
    for my $Needed (qw(DebuggerObject WebserviceID)) {
        if ( !$Param{$Needed} ) {
            return {
                Success      => 0,
                ErrorMessage => "Got no $Needed!",
            };
        }

        $Self->{$Needed} = $Param{$Needed};
    }

    # get config for this screen
    #$Self->{Config} = $Kernel::OM->Get('Kernel::Config')->Get('GenericInterface::Operation::GeneralCatalogGetValues');

    return $Self;
}

=pod
@api {post} /ticket/attachment/get Get Attachment Content from a ticket.
@apiName Attachment Get
@apiGroup Ticket
@apiVersion 1.0.0

@apiExample Example usage:
  {
    "SessionID": "vbX9n8cxJSdig0QODzl3Vrl74ip6jNGP",
    "TicketID": 4,
    "ArticleID": 36,
    "FileID": 1
  }

@apiParam (Request body) {String} [UserLogin] User login to create sesssion.
@apiParam (Request body) {String} [Password] Password to create session.
@apiParam (Request body) {String} SessionID session id generated by session create method.
@apiParam (Request body) {Integer} TicketID Ticket ID.
@apiParam (Request body) {Integer} ArticleID Article ID.
@apiParam (Request body) {Integer} FileID File ID.

@apiErrorExample {json} Error example:
  HTTP/1.1 200 Success
  {
    "Error": {
      "ErrorCode": "ArticleAttachmentGet.AuthFail",
      "ErrorMessage": "ArticleAttachmentGet: Authorization failing!"
    }
  }
@apiSuccessExample {json} Success example:
  HTTP/1.1 200 Success
  {
    "FileContent": "77u/VGVzdGUgUmljYXJkbw=="
  }
=cut
sub Run {
    my ( $Self, %Param ) = @_;

    my ( $UserID, $UserType ) = $Self->Auth(
        %Param,
    );

    my $TypeObject = $Kernel::OM->Get('Kernel::System::Type');

    return $Self->ReturnError(
        ErrorCode    => 'GeneralCatalogGetValues.AuthFail',
        ErrorMessage => "GeneralCatalogGetValues: Authorization failing!",
    ) if !$UserID;

    for my $Needed (qw( TicketID ArticleID FileID )) {
        if ( !$Param{Data}->{$Needed} ) {

            return $Self->ReturnError(
                ErrorCode    => 'SessionCreate.MissingParameter',
                ErrorMessage => "SessionCreate: $Needed parameter is missing!",
            );
        }
    }

    my $ArticleObject = $Kernel::OM->Get('Kernel::System::Ticket::Article');
    my $ArticleBackendObject = $ArticleObject->BackendForArticle( TicketID => $Param{Data}->{TicketID}, ArticleID => $Param{Data}->{ArticleID} );

    my %Attachment = $ArticleBackendObject->ArticleAttachment(
        ArticleID => $Param{Data}->{ArticleID},
        FileID    => $Param{Data}->{FileID},                 # as returned by ArticleAttachmentIndex
        UserID    => $UserID,
    );

    if(%Attachment){

        return {
            Success => 1,
            Data    => {
                FileContent => MIME::Base64::encode_base64( $Attachment{Content},'' )
            },
        };
    }

    return {
        Success => 1,
        Data    => {},
    };
    
}

1;

=back

=head1 TERMS AND CONDITIONS

This software is part of the OTRS project (L<http://otrs.org/>).

This software comes with ABSOLUTELY NO WARRANTY. For details, see
the enclosed file COPYING for license information (AGPL). If you
did not receive this file, see L<http://www.gnu.org/licenses/agpl.txt>.

=cut